# Generated by Django 2.0.7 on 2020-08-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200825_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='NO REGISTERS', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete='SET NULL', to='posts.Countries'),
        ),
    ]
